# Generated by Django 4.1 on 2022-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_alter_book_stock_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Anunay', max_length=100),
        ),
    ]
